### ISSUE TITLE
23 tests fail on stable-x86_64-apple-darwin - 1.53.0 (53cb7b09b 2021-06-17)

### ISSUE THREAD

**Issue by jayvdb** [sagiegurari/cargo-make#573]
### Describe The Bug
I am seeing the following errors running `cargo test` on latest stable and nightly:
-  condition::condition_test::validate_criteria_invalid_file_not_exists
-   condition::condition_test::validate_criteria_valid_file_exists
-  condition::condition_test::validate_file_exists_valid
-  condition::condition_test::validate_file_not_exists_invalid
-   condition::condition_test::validate_file_not_exists_partial_invalid
-  descriptor::makefiles::mod_test::makefile_audit_test
-  descriptor::makefiles::mod_test::makefile_outdated_test
-   installer::crate_version_check::crate_version_check_test::load_crates_toml_file_not_found
-  installer::crate_version_check::crate_version_check_test::load_crates_toml_valid
-  runner::runner_test::create_fork_step_valid
-  runner::runner_test::get_sub_task_info_for_routing_info_condition_found
-  runner::runner_test::get_sub_task_info_for_routing_info_condition_found_multiple_tasks
-  runner::runner_test::get_sub_task_info_for_routing_info_default
-  runner::runner_test::get_sub_task_info_for_routing_info_fork_false
-  runner::runner_test::get_sub_task_info_for_routing_info_fork_true
-   runner::runner_test::get_sub_task_info_for_routing_info_multiple
-  runner::runner_test::get_sub_task_info_for_routing_info_multiple_found
-   scriptengine::mod_test::get_script_text_file
-   scriptengine::mod_test::get_script_text_file_absolute
-   scriptengine::mod_test::get_script_text_file_relative
-  toolchain::toolchain_test::wrap_command_empty_args
-  toolchain::toolchain_test::wrap_command_none_args
-   toolchain::toolchain_test::wrap_command_with_args

Possibly most of these are a result of the failures at https://github.com/sagiegurari/duckscript/issues/185

### To Reproduce
1. rustup update
2. cargo test

```rust
failures:

---- condition::condition_test::validate_criteria_invalid_file_not_exists stdout ----
thread 'condition::condition_test::validate_criteria_invalid_file_not_exists' panicked at 'assertion failed: !enabled', src/lib/condition_test.rs:1795:5

---- condition::condition_test::validate_criteria_valid_file_exists stdout ----
thread 'condition::condition_test::validate_criteria_valid_file_exists' panicked at 'assertion failed: enabled', src/lib/condition_test.rs:1645:5

---- condition::condition_test::validate_file_exists_valid stdout ----
thread 'condition::condition_test::validate_file_exists_valid' panicked at 'assertion failed: enabled', src/lib/condition_test.rs:1068:5

---- condition::condition_test::validate_file_not_exists_invalid stdout ----
thread 'condition::condition_test::validate_file_not_exists_invalid' panicked at 'assertion failed: !enabled', src/lib/condition_test.rs:1195:5

---- condition::condition_test::validate_file_not_exists_partial_invalid stdout ----
thread 'condition::condition_test::validate_file_not_exists_partial_invalid' panicked at 'assertion failed: !enabled', src/lib/condition_test.rs:1170:5

---- descriptor::makefiles::mod_test::makefile_audit_test stdout ----
thread 'descriptor::makefiles::mod_test::makefile_audit_test' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', src/lib/descriptor/makefiles/mod_test.rs:66:9

---- descriptor::makefiles::mod_test::makefile_outdated_test stdout ----
thread 'descriptor::makefiles::mod_test::makefile_outdated_test' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', src/lib/descriptor/makefiles/mod_test.rs:66:9

---- installer::crate_version_check::crate_version_check_test::load_crates_toml_file_not_found stdout ----
thread 'installer::crate_version_check::crate_version_check_test::load_crates_toml_file_not_found' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/john.vandenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/envmnt-0.9.0/src/environment.rs:53:19

---- installer::crate_version_check::crate_version_check_test::load_crates_toml_valid stdout ----
thread 'installer::crate_version_check::crate_version_check_test::load_crates_toml_valid' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/john.vandenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/envmnt-0.9.0/src/environment.rs:53:19

---- runner::runner_test::create_fork_step_valid stdout ----
thread 'runner::runner_test::create_fork_step_valid' panicked at 'assertion failed: `(left == right)`
  left: `8`,
 right: `10`', src/lib/runner_test.rs:2271:5

---- runner::runner_test::get_sub_task_info_for_routing_info_condition_found stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_condition_found' panicked at 'called `Option::unwrap()` on a `None` value', src/lib/runner_test.rs:1733:26

---- runner::runner_test::get_sub_task_info_for_routing_info_condition_found_multiple_tasks stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_condition_found_multiple_tasks' panicked at 'called `Option::unwrap()` on a `None` value', src/lib/runner_test.rs:1791:26

---- runner::runner_test::get_sub_task_info_for_routing_info_default stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_default' panicked at 'assertion failed: `(left == right)`
  left: `["test1"]`,
 right: `["default"]`', src/lib/runner_test.rs:2023:5

---- runner::runner_test::get_sub_task_info_for_routing_info_fork_false stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_fork_false' panicked at 'called `Option::unwrap()` on a `None` value', src/lib/runner_test.rs:2165:26

---- runner::runner_test::get_sub_task_info_for_routing_info_fork_true stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_fork_true' panicked at 'called `Option::unwrap()` on a `None` value', src/lib/runner_test.rs:2223:26

---- runner::runner_test::get_sub_task_info_for_routing_info_multiple stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_multiple' panicked at 'assertion failed: `(left == right)`
  left: `["test1"]`,
 right: `["test3"]`', src/lib/runner_test.rs:2107:5

---- runner::runner_test::get_sub_task_info_for_routing_info_multiple_found stdout ----
thread 'runner::runner_test::get_sub_task_info_for_routing_info_multiple_found' panicked at 'assertion failed: `(left == right)`
  left: `["test2"]`,
 right: `["test1"]`', src/lib/runner_test.rs:1947:5

---- scriptengine::mod_test::get_script_text_file stdout ----
thread 'scriptengine::mod_test::get_script_text_file' panicked at 'Unable to read file: "${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt" error: IOError(
    "Unable to read file: \"${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt\"",
    Some(
        Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory",
        },
    ),
)', src/lib/io.rs:66:23

---- scriptengine::mod_test::get_script_text_file_absolute stdout ----
thread 'scriptengine::mod_test::get_script_text_file_absolute' panicked at 'Unable to read file: "${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt" error: IOError(
    "Unable to read file: \"${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt\"",
    Some(
        Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory",
        },
    ),
)', src/lib/io.rs:66:23

---- scriptengine::mod_test::get_script_text_file_relative stdout ----
thread 'scriptengine::mod_test::get_script_text_file_relative' panicked at 'Unable to read file: "${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt" error: IOError(
    "Unable to read file: \"${CARGO_MAKE_WORKING_DIRECTORY}/src/lib/test/test_files/text_file.txt\"",
    Some(
        Os {
            code: 2,
            kind: NotFound,
            message: "No such file or directory",
        },
    ),
)', src/lib/io.rs:66:23

---- toolchain::toolchain_test::wrap_command_empty_args stdout ----
thread 'toolchain::toolchain_test::wrap_command_empty_args' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/john.vandenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/envmnt-0.9.0/src/environment.rs:53:19

---- toolchain::toolchain_test::wrap_command_none_args stdout ----
thread 'toolchain::toolchain_test::wrap_command_none_args' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/john.vandenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/envmnt-0.9.0/src/environment.rs:53:19

---- toolchain::toolchain_test::wrap_command_with_args stdout ----
thread 'toolchain::toolchain_test::wrap_command_with_args' panicked at 'called `Result::unwrap()` on an `Err` value: NotPresent', /Users/john.vandenberg/.cargo/registry/src/github.com-1ecc6299db9ec823/envmnt-0.9.0/src/environment.rs:53:19


failures:
    condition::condition_test::validate_criteria_invalid_file_not_exists
    condition::condition_test::validate_criteria_valid_file_exists
    condition::condition_test::validate_file_exists_valid
    condition::condition_test::validate_file_not_exists_invalid
    condition::condition_test::validate_file_not_exists_partial_invalid
    descriptor::makefiles::mod_test::makefile_audit_test
    descriptor::makefiles::mod_test::makefile_outdated_test
    installer::crate_version_check::crate_version_check_test::load_crates_toml_file_not_found
    installer::crate_version_check::crate_version_check_test::load_crates_toml_valid
    runner::runner_test::create_fork_step_valid
    runner::runner_test::get_sub_task_info_for_routing_info_condition_found
    runner::runner_test::get_sub_task_info_for_routing_info_condition_found_multiple_tasks
    runner::runner_test::get_sub_task_info_for_routing_info_default
    runner::runner_test::get_sub_task_info_for_routing_info_fork_false
    runner::runner_test::get_sub_task_info_for_routing_info_fork_true
    runner::runner_test::get_sub_task_info_for_routing_info_multiple
    runner::runner_test::get_sub_task_info_for_routing_info_multiple_found
    scriptengine::mod_test::get_script_text_file
    scriptengine::mod_test::get_script_text_file_absolute
    scriptengine::mod_test::get_script_text_file_relative
    toolchain::toolchain_test::wrap_command_empty_args
    toolchain::toolchain_test::wrap_command_none_args
    toolchain::toolchain_test::wrap_command_with_args

test result: FAILED. 665 passed; 23 failed; 222 ignored; 0 measured; 0 filtered out; finished in 4.05s
```

**Comment by jayvdb** [comment]
If I run `cargo make test` or `cargo make ci-flow`, there are no errors, and it ends with
> test result: ok. 688 passed; 0 failed; 222 ignored; 0 measured; 0 filtered out; finished in 5.06s

So I am guessing these tests are known to not pass under the default `cargo test`.  Perhaps they can be disabled so `cargo test` works.

**Comment by sagiegurari** [comment]
you must use cargo make to run the test. some of them aee not thread safe and cargo make splits those so some run single threaded.
