### ISSUE TITLE
Remove OpenSSL

### ISSUE THREAD

**Issue by MartinKavik** [sagiegurari/cargo-make#614]
### Feature Description
We would like to remove OpenSSL dependency from `cargo-make` because it's painful to setup on some platforms.

### Describe The Solution You'd Like
Remove native dependencies like OpenSSL if possible.

---

@arn-the-long-beard Could you provide more details / your experience?

**Comment by arn-the-long-beard** [comment]
Thank you @MartinKavik  :wink: 

Yes well, we do use `cargo-make` a lot because it is a great tool :smile: .

And many times when I setup a new OS for one of my teammate, I do or **not** encounter   compilation error due to OpenSSL, environment variables when running `cargo install --force cargo-make`. 


Today I got new errors on a fresh install for Linux (Arch) Manjaro. 
But the **same** computer this summer, with the same OS ( and version) and it was no issues. 

First we got this :
```


Could not find directory of OpenSSL installation, and this -sys crate cannot
  proceed without this knowledge. If OpenSSL is installed and this crate had
  trouble finding it,  you can set the OPENSSL_DIR environment variable for the
  compilation process.
//// More
```

Then after fixing the environment variable :

```
export OPENSSL_DIR="/etc"
export OPENSSL_INCLUDE_DIR="/usr/include/openssl"

```
We got this :

```

error: failed to run custom build command for openssl-sys v0.9.71

Caused by:
  process didn't exit successfully: /tmp/cargo-install3gVNGG/release/build/openssl-sys-37a921daded85d66/build-script-main (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
  OPENSSL_LIB_DIR unset
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
  OPENSSL_INCLUDE_DIR = /usr/include/openssl
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR unset
  cargo:rerun-if-env-changed=OPENSSL_DIR
  OPENSSL_DIR = /etc

  --- stderr
  thread 'main' panicked at 'OpenSSL library directory does not exist: /etc/lib', /home/[My programmer name ]/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.71/build/main.rs:68:9
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile cargo-make v0.35.6, intermediate artifacts can be found at /tmp/cargo-install3gVNGG

```



Then we fixed this with :

```
export OPENSSL_DIR="/etc/"
export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR="/lib/"
export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR="/lib/"
export X86_64_UNKNOWN_LINUX_GNU_OPENSSL_DIR="/lib/"
```


`sudo nano /etc/bash.bashrc`


and then 

`pacman -S pkg-config`

Then it seemed everything was fine, but then we got this while doing `cargo make watch´


```


error: failed to run custom build command for `openssl-sys v0.9.71`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installDzysoq/release/build/openssl-sys-2e3c3024dbc7d95d/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/tmp/cargo-installDzysoq/release/build/openssl-sys-ddae2c1473b9066c/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 3.0.0 for target linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Running configdata.pm
  Creating Makefile.in
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL.md file first)      ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/[My programmer name] /.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-300.0.2+3.0.0/src/lib.rs:490:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-installDzysoq`

```


I asked my teammate to open an issue  and he did it there :

https://github.com/openssl/openssl/issues/17223

( He is editing the issue right now, he just miss clicked when he made the post )


My teammate is not a Linux guy, he is new to it. And I have some knowledge on Linux so first time on my own computer I used one good day of work to make research and fix the issue and I succeed. But the last bug we have while running `cargo make watch` , I have no idea how to solve this and I actually don't have the time.

From a user point of view, this difficulties are not programming things and the gap vs knowledge we need is far from our current skills and target. So I think that removing the dependency would be a great path to better user experience :smile: 

Please ask me if you need more information.

**Comment by sagiegurari** [comment]
question, why not just download the precompiled binaries from the releases?

**Comment by MartinKavik** [comment]
> question, why not just download the precompiled binaries from the releases?

- I often switch platforms/machines and use different build pipelines with `cargo-make` so both installation and updating is easier with `cargo install cargo-make` for me. 
- Onboarding new users to open-source projects is easier with simpler commands / steps - it's annoying for users when they have to manually download and install (multiple) tools (e.g. Rust, cargo make, wasm-pack, etc.). Also there is a higher chance they won't update the tools so they will report issues caused by out-of-date tooling (based on experience).

I use precompiled binaries only when I really need to save some time that would otherwise be consumed by the slow Rust compilation.

**Comment by arn-the-long-beard** [comment]
> question, why not just download the precompiled binaries from the releases?

Well I didn't know this was possible, I have never done it before.  I made a quick search for installing binaries on google but I am not sure where to start. What is your recommendation/guideline to install precompiled binaries ? 

Now questions : 

- If I get the binaries, does it solve all the Openssl issues we have?

- What is openssl used for in `cargo-make` ? 

- `cargo-make` is super practical and used a lot, we are not the only one who had this pain with openssl. We can take this problem and turn it into an opportunity to improve :wink:  . What do you think ? I would be happy to contribute and workout a solution if possible :smile: .

**Comment by sagiegurari** [comment]
* to use precompiled cargo-make executable, just go to the releases at:
https://github.com/sagiegurari/cargo-make/releases
download the binary you want (window, mac, linux)
and put it in your cargo/bin directory (if you use makers executable and not 'cargo make' executable, than just put it anywhere in your path).
I wrote a bit about it here:
https://github.com/sagiegurari/cargo-make#installation-binary-release
although i now see i wrote about arm as well, but i no longer support it :(
need to fix the readme

* openssl is used (need to check if other places as well) in duckscript.
duckscript is a shell like lang+runtime so you can run scripts that are cross platform (windows and linux for example...).
it comes with a sdk so you can get things going fast.
see commands available by default:
https://github.com/sagiegurari/duckscript/blob/master/docs/sdk.md
and some commands use openssl. well.... i think only the http_client and wget commands.
I could make it optional in duckscript and in cargo-make to prevent the need for openssl.
might take a bit to make it happen (a bit busy), so if anyone wants to PR both projects to make it happen i'll be more than happy to review and accept.

**Comment by arn-the-long-beard** [comment]
Okay, thank you so much for your answer :100: :wink: 

- We will try to install the binaries right now and see how it solve the issues.


- I will take a look on spare time I think. Not sure I have the level to understand but I 'll give a try :+1: 

So to resume, 

1 - Check duckscript and see how to make `openssl` optional.
2 - Check `cargo-make` and see how to make `openssl` optional there as well.

Sounds like a good plan for you ?

**Comment by sagiegurari** [comment]
ya, plan sounds right.
basically it means to define a feature in both crates.
and for each to update the dependencies based on that.
i am not sure if there is a need for code changes.
i might be able to take a look this weekend on it. i hope :)

**Comment by arn-the-long-beard** [comment]
Well, we did install the binaries as suggested. And the bug number 3 still appear : 

```
error: failed to run custom build command for `openssl-sys v0.9.71`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installf4yzDF/release/build/openssl-sys-2e3c3024dbc7d95d/build-script-main` (exit status: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/tmp/cargo-installf4yzDF/release/build/openssl-sys-ddae2c1473b9066c/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64"
  Configuring OpenSSL version 3.0.0 for target linux-x86_64
  Using os-specific seed configuration
  Creating configdata.pm
  Running configdata.pm
  Creating Makefile.in
  Creating Makefile

  **********************************************************************
  ***                                                                ***
  ***   OpenSSL has been successfully configured                     ***
  ***                                                                ***
  ***   If you encounter a problem while building, please open an    ***
  ***   issue on GitHub <https://github.com/openssl/openssl/issues>  ***
  ***   and include the output from the following command:           ***
  ***                                                                ***
  ***       perl configdata.pm --dump                                ***
  ***                                                                ***
  ***   (If you are new to OpenSSL, you might want to consult the    ***
  ***   'Troubleshooting' section in the INSTALL.md file first)      ***
  ***                                                                ***
  **********************************************************************
  running "make" "depend"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/[My Programmer Name]/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-300.0.2+3.0.0/src/lib.rs:490:39
  stack backtrace:
     0:     0x55d0b36af24c - std::backtrace_rs::backtrace::libunwind::trace::hf6a6dfd7da937cb0
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x55d0b36af24c - std::backtrace_rs::backtrace::trace_unsynchronized::hc596a19e4891f7f3
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55d0b36af24c - std::sys_common::backtrace::_print_fmt::hb16700db31584325
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x55d0b36af24c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h231c4190cfa75162
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x55d0b36d0a5c - core::fmt::write::h2a1462b5f8eea807
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/fmt/mod.rs:1163:17
     5:     0x55d0b36ab015 - std::io::Write::write_fmt::h71ddfebc68685972
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/io/mod.rs:1696:15
     6:     0x55d0b36b19c0 - std::sys_common::backtrace::_print::hcc197d4bebf2b369
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x55d0b36b19c0 - std::sys_common::backtrace::print::h335a66af06738c7c
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x55d0b36b19c0 - std::panicking::default_hook::{{closure}}::h6fac9ac9c8b79e52
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:210:50
     9:     0x55d0b36b1575 - std::panicking::default_hook::h341c1030c6a1161b
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:227:9
    10:     0x55d0b36b2074 - std::panicking::rust_panic_with_hook::h50680ff4b44510c6
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:624:17
    11:     0x55d0b36b1b50 - std::panicking::begin_panic_handler::{{closure}}::h9371c0fbb1e8465a
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:521:13
    12:     0x55d0b36af6f4 - std::sys_common::backtrace::__rust_end_short_backtrace::h9b3efa22a5768c0f
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/sys_common/backtrace.rs:139:18
    13:     0x55d0b36b1ab9 - rust_begin_unwind
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
    14:     0x55d0b35f0191 - core::panicking::panic_fmt::h23b9203e89cc61cf
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
    15:     0x55d0b35f0223 - core::result::unwrap_failed::h32ef6b3156e8fc57
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
    16:     0x55d0b362a369 - core::result::Result<T,E>::unwrap::h2865b71e4218a13e
    17:     0x55d0b3628f1a - openssl_src::Build::run_command::ha1416688064c800e
    18:     0x55d0b36283ed - openssl_src::Build::build::h6c86759f0a576f90
    19:     0x55d0b35f9038 - build_script_main::find_vendored::get_openssl::h2291d2abdfa848ad
    20:     0x55d0b35f2bc5 - build_script_main::find_openssl::h84c8a0ee9f0564a8
    21:     0x55d0b35f2cbf - build_script_main::main::h6c0e920944e75b39
    22:     0x55d0b35f86e3 - core::ops::function::FnOnce::call_once::he515030babb2d7c1
    23:     0x55d0b35f85b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf8aa07716b155daa
    24:     0x55d0b35f7079 - std::rt::lang_start::{{closure}}::h18f8d371d52c98cb
    25:     0x55d0b36aef2b - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hc56adab7a77ec6e3
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/ops/function.rs:259:13
    26:     0x55d0b36aef2b - std::panicking::try::do_call::h29f013120c5abc65
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
    27:     0x55d0b36aef2b - std::panicking::try::h86d5b2b66caec4cf
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
    28:     0x55d0b36aef2b - std::panic::catch_unwind::h7dd136d787f51397
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
    29:     0x55d0b36aef2b - std::rt::lang_start_internal::{{closure}}::h4a199351e630a8a5
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:48
    30:     0x55d0b36aef2b - std::panicking::try::do_call::h20ceb9e5dff838c6
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:403:40
    31:     0x55d0b36aef2b - std::panicking::try::hc2abb46a5e41bd43
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:367:19
    32:     0x55d0b36aef2b - std::panic::catch_unwind::h52c3eb4408ad6dfb
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panic.rs:133:14
    33:     0x55d0b36aef2b - std::rt::lang_start_internal::hd15a47be08101c28
                                 at /rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/rt.rs:128:20
    34:     0x55d0b35f7061 - std::rt::lang_start::h87f666f8683eac11
    35:     0x55d0b35f6943 - main
    36:     0x7f72a2871b25 - __libc_start_main
    37:     0x55d0b35f090e - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `wasm-pack v0.10.1`, intermediate artifacts can be found at `/tmp/cargo-installf4yzDF`

Caused by:
  build failed
[cargo-make][2] ERROR - Error while executing command, exit code: 101
[cargo-make][2] WARN - Build Failed.

```

So I am not sure what we can do.

**Comment by sagiegurari** [comment]
ok so wasm-pack also needs openssl? if so, removing it from cargo-make won't really help much as wasm-pack is not part of cargo-make. 
cargo-make installs it if needed same as it installs any tool that might be requested/needed by a given task (a bit on that here: https://github.com/sagiegurari/cargo-make#installing-dependencies)

**Comment by arn-the-long-beard** [comment]
Yes good points.

**Comment by arn-the-long-beard** [comment]
Well, my colleague installed `wasm-pack` globally with this link  https://rustwasm.github.io/wasm-pack/installer/  and he has been able to work now.

It seems that `cargo-make` was downloading `wasm-pack` binaries, this is why he got the last glitch.

So we can still find a way to improve `cargo-make` by removing the dependency :smile:

**Comment by sagiegurari** [comment]
@MartinKavik  @arn-the-long-beard this is now implemented in the dev branch.
Basically there is now a tls feature (on by default).
so when installing, use the **--no-default-features** flag to the cargo install command.
I would love your feedback to make sure it works well for you (don't forget to install from the dev branch, not crates.io).

**Comment by sagiegurari** [comment]
@MartinKavik @arn-the-long-beard this is now officially released (needed to release a new version due to other issue) so you can try it out on the latest crates.io version.
if there is any issue with it (or other issues) feel free to open.

**Comment by arn-the-long-beard** [comment]
Thank you mate !!! We are going to try it. I'll give you a feedback as soon as possible :smile:

**Comment by osain-az** [comment]
@sagiegurari.  We have tried it but still having  the same issue. 

procedure of what  was done.

1:  In  the Cargo  folder,  the  `cargo-make`  folder was deleted. 
2:  Then  install cargo make  by  `cargo install cargo-make`.
2:  Then run  `cargo  make watch` 

We still have the same  error as mentioned earlier. 
Is there something  that  is missing ? 

Thank you

**Comment by sagiegurari** [comment]
yes. you must use the  --no-default-features  as i wrote in my comments

**Comment by osain-az** [comment]
> 

With the ` -no-default-features  `  option, after installing everything work fine . 

Thanks

**Comment by Ding-Fan** [comment]
> > 
> 
> With the `-no-default-features ` option, after installing everything work fine .
> 
> Thanks

`--no-default-features` it is double dash in it :eyes:
