### ISSUE TITLE
Panic checking if crate needs to be installed

### ISSUE THREAD

**Issue by Person-93** [sagiegurari/cargo-make#615]
### Describe The Bug
Cargo make panics while checking if a crate needs to be installed if the args are set like this: `args = ["${@}"]`

### To Reproduce
Copy this task into your Makefile.toml and try to run it.
```toml
[tasks.bacon]
condition = { profiles = ["development"] }
install_crate = { crate_name = "bacon", min_version = "1.2.4" }
command = "bacon"
args = ["${@}"]
```

### Error Stack

```console
$ cargo make bacon
[cargo-make] INFO - cargo make 0.35.6
[cargo-make] INFO - Project: test-project
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: bacon
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', /.cargo/registry/src/github.com-1ecc6299db9ec823/cargo-make-0.35.6/src/lib/installer/mod.rs:90:38
stack backtrace:
   0:     0x56002065a3fc - std::backtrace_rs::backtrace::libunwind::trace::hd3a6cb8e32f9fc43
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x56002065a3fc - std::backtrace_rs::backtrace::trace_unsynchronized::h6dcceebcd6a9f2ab
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x56002065a3fc - std::sys_common::backtrace::_print_fmt::h4eacf4e9ad977499
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x56002065a3fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h1e42c22572a7e7b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x560020682f3c - core::fmt::write::h072b578a8e90aa54
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/fmt/mod.rs:1150:17
   5:     0x560020652605 - std::io::Write::write_fmt::hc32d3cabefff1d24
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/io/mod.rs:1667:15
   6:     0x56002065c520 - std::sys_common::backtrace::_print::h058b85b6efc15780
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x56002065c520 - std::sys_common::backtrace::print::hdb7de10b704104b4
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x56002065c520 - std::panicking::default_hook::{{closure}}::h5451997d203bda2f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:210:50
   9:     0x56002065c0d7 - std::panicking::default_hook::h419b121e68f746a2
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:227:9
  10:     0x56002065cbd4 - std::panicking::rust_panic_with_hook::h32c44b1364c1c247
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:624:17
  11:     0x56002065c6b0 - std::panicking::begin_panic_handler::{{closure}}::he2e5f48fb16982d1
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:521:13
  12:     0x56002065a8a4 - std::sys_common::backtrace::__rust_end_short_backtrace::haea54a33f9e18aba
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x56002065c619 - rust_begin_unwind
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
  14:     0x56002008ac01 - core::panicking::panic_fmt::h824e0febbdf5e655
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
  15:     0x56002008abc2 - core::panicking::panic_bounds_check::h1b36860099eee6dd
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:77:5
  16:     0x56002027b621 - cli::installer::install::h9417f9860fadeaeb
  17:     0x560020327730 - cli::runner::run_task::ha680bf88d0048602
  18:     0x56002032998e - cli::runner::run_flow::h5e450d358862cfdf
  19:     0x560020329e0c - cli::runner::run::h2b8ce12dd6306f0d
  20:     0x5600200b5aaf - cli::cli::run_cli::hbe77e61bcadbe8a2
  21:     0x5600200a001c - cli::run_cli::hcf3a2d6303b5b69c
  22:     0x56002008b4dd - cargo_make::main::hb13b87fd2172de9e
  23:     0x56002008b533 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd9d84c722075202e
  24:     0x56002008b549 - std::rt::lang_start::{{closure}}::hdc3e9cd31c7e4ab0
  25:     0x56002065d1da - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h97e9d5f21cbee92f
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/ops/function.rs:259:13
  26:     0x56002065d1da - std::panicking::try::do_call::hdfecd950eba8f698
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  27:     0x56002065d1da - std::panicking::try::h3c77c8ba3eb0735c
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  28:     0x56002065d1da - std::panic::catch_unwind::h8e0d62076d8d837e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  29:     0x56002065d1da - std::rt::lang_start_internal::{{closure}}::h647045b4c6a22e67
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:48
  30:     0x56002065d1da - std::panicking::try::do_call::h905d96e4a757647e
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:403:40
  31:     0x56002065d1da - std::panicking::try::hc113426beb3c908b
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:367:19
  32:     0x56002065d1da - std::panic::catch_unwind::h74f684ea7038ea12
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panic.rs:129:14
  33:     0x56002065d1da - std::rt::lang_start_internal::h5ba185919d396c97
                               at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/rt.rs:45:20
  34:     0x56002008b522 - main
  35:     0x7f7002eb0d0a - __libc_start_main
                               at ./csu/../csu/libc-start.c:308:16
  36:     0x56002008b3da - _start
  37:                0x0 - <unknown>
```

**Comment by sagiegurari** [comment]
@Person-93 thanks a lot for reporting.
I've fixed it now in the dev branch.

**Comment by sagiegurari** [comment]
@Person-93 this is now officially released. thanks a lot for reporting it
