### ISSUE TITLE
Parallel flag conflicts with path because of race condition

### ISSUE THREAD

**Issue by strowk** [sagiegurari/cargo-make#709]
### Describe The Bug
I would like to have a setup with two services having their own separate Makefile.toml files and another root Makefile to rule them all.

One of tasks I want to add is `start`, which is supposed to be watching for changes and running `run` whenever something is changed. Unfortunately, I have run in the problem in that combination of run_task and dependencies with path, seem to be working quite wrong. It appears that change in directory is shared between both tasks for some reason (probably lack of isolation).

### To Reproduce

For example following setup could be used to reproduce:

Create folders srv1 and srv2, place there a Makefile.toml with something simple like this: 
```
[tasks.pwd]
command = "pwd"
```

Now in root create following Makefile.toml:
```
[tasks.pwd]
run_task = { name = ["pwd-srv1", "pwd-srv2"], parallel = true}

[tasks.pwd-srv1]
dependencies = [ { name = "pwd", path = "srv1/Makefile.toml" } ]

[tasks.pwd-srv2]
dependencies = [ { name = "pwd", path = "srv2/Makefile.toml" } ]
```

What happens when you run `cargo make pwd` depends on race condition outcome.

In some situations you might see following output:
```
[cargo-make][1] INFO - Execute Command: "pwd"
/c/work/testbug/srv2
[←[1mcargo-make←[0m][1] ←[1;32mINFO←[0m - Build Done in 0.21 seconds.
/c/work/testbug/srv2
[←[1mcargo-make←[0m][1] ←[1;32mINFO←[0m - Build Done in 0.21 seconds.
[←[1mcargo-make←[0m] ←[1;32mINFO←[0m - Build Done in 0.52 seconds.
```

This shows that both tasks have in fact executed within the same directory, which is not expected.

In some other situations following could happen: 
```
[cargo-make] ERROR - Unable to set current working directory to: srv2/Makefile.toml Os {
    code: 267,
    kind: NotADirectory,
    message: "The directory name is invalid.",
}
```

Yet in some other situations (not for empty service though, when some code is made too), I have seen cargo make to panic.
(though this is comparable rare)

### Error Stack

```console
[←[1mcargo-make←[0m][1] ←[1;32mINFO←[0m - Build Done in 0.48 seconds.
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', C:\Users\strow\.cargo\registry\src\github.com-1ecc6299db9ec823\cargo-make-0.36.0\src/lib\runner.rs:236:36
stack backtrace:
   0:     0x7ff64cb40900 - std::backtrace_rs::backtrace::dbghelp::trace::hfba897a698a859e6
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace/dbghelp.rs:98:5
   1:     0x7ff64cb40900 - std::backtrace_rs::backtrace::trace_unsynchronized::he4eb3fd9cb4c57fe
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\..\..\backtrace\src\backtrace/mod.rs:66:5
   2:     0x7ff64cb40900 - std::sys_common::backtrace::_print_fmt::hcb44c974f53661c3
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common/backtrace.rs:66:5
   3:     0x7ff64cb40900 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h80a12eeaf48b9d9c
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common/backtrace.rs:45:22
   4:     0x7ff64cb9b53a - core::fmt::write::h32715354180621d4
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src\fmt/mod.rs:1190:17
   5:     0x7ff64cb315d9 - std::io::Write::write_fmt::hc97d08873315f559
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\io/mod.rs:1657:15
   6:     0x7ff64cb43cde - std::sys_common::backtrace::_print::h92a98b7a6e221589
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common/backtrace.rs:48:5
   7:     0x7ff64cb43cde - std::sys_common::backtrace::print::hed4f70c57c6700f8
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common/backtrace.rs:35:9
   8:     0x7ff64cb43cde - std::panicking::default_hook::{{closure}}::hb1992f6adf5cc4a6
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:295:22
   9:     0x7ff64cb43969 - std::panicking::default_hook::h00b5ae6fa72c5dc3
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:314:9
  10:     0x7ff64cb4441d - std::panicking::rust_panic_with_hook::h33a5104d42e97829
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:698:17
  11:     0x7ff64cb44305 - std::panicking::begin_panic_handler::{{closure}}::hbc930326febf8af2
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:588:13
  12:     0x7ff64cb41307 - std::sys_common::backtrace::__rust_end_short_backtrace::h153075b053bda0c5
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src\sys_common/backtrace.rs:138:18
  13:     0x7ff64cb44019 - rust_begin_unwind
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:584:5
  14:     0x7ff64cb97f95 - core::panicking::panic_fmt::h58120d9d2ee1006b
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src/panicking.rs:143:14
  15:     0x7ff64cb982f3 - core::result::unwrap_failed::h09f55ed979506385
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\core\src/result.rs:1749:5
  16:     0x7ff64c446059 - cli::runner::run_sub_task_and_report::hdf5eba17814c09f3
  17:     0x7ff64c449320 - cli::runner::run_task_with_options::hbd34b8384e53542f
  18:     0x7ff64c4498ca - cli::runner::run_flow::ha7252aec43bf2e80
  19:     0x7ff64c449df1 - cli::runner::run::hdc62f2308b044f4a
  20:     0x7ff64c31c40c - cli::cli::run_cli::hdd93747e49fd2e7a
  21:     0x7ff64c2f3d9f - cli::run_cli::haf2fc7fbc8c03388
  22:     0x7ff64c2e163b - cargo_make::main::hd85167e8acd53668
  23:     0x7ff64c2e1596 - std::sys_common::backtrace::__rust_begin_short_backtrace::h33ffe7fb425a3ef5
  24:     0x7ff64c2e171c - std::rt::lang_start::{{closure}}::hb1daaa582cd011f4
  25:     0x7ff64cb402ab - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h09e7bc7b2dde001e
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\library\core\src\ops/function.rs:259:13
  26:     0x7ff64cb402ab - std::panicking::try::do_call::h26a16fee3ee717ef
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:492:40
  27:     0x7ff64cb402ab - std::panicking::try::hbaf3d03192b6828f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:456:19
  28:     0x7ff64cb402ab - std::panic::catch_unwind::h3c6b612522b1b17f
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panic.rs:137:14
  29:     0x7ff64cb402ab - std::rt::lang_start_internal::{{closure}}::he40eaf90b421e965
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/rt.rs:128:48
  30:     0x7ff64cb402ab - std::panicking::try::do_call::hf73a74aaf5e4b9ec
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:492:40
  31:     0x7ff64cb402ab - std::panicking::try::h76fb6e510f8a4c72
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panicking.rs:456:19
  32:     0x7ff64cb402ab - std::panic::catch_unwind::hbe033c136e3d65cf
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/panic.rs:137:14
  33:     0x7ff64cb402ab - std::rt::lang_start_internal::hea5ca44c01326960
                               at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c\/library\std\src/rt.rs:128:20
  34:     0x7ff64c2e1698 - main
  35:     0x7ff64c2e13b1 - __tmainCRTStartup
                               at C:\M\mingw-w64-crt-git\src\crt-x86_64-w64-mingw32\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:321:15
  36:     0x7ff64c2e14e6 - mainCRTStartup
                               at C:\M\mingw-w64-crt-git\src\crt-x86_64-w64-mingw32\C:/M/mingw-w64-crt-git/src/mingw-w64/mingw-w64-crt/crt\crtexe.c:202:9
  37:     0x7ffbcaf954e0 - <unknown>
  38:     0x7ffbcb4e485b - <unknown>

```

**Comment by strowk** [comment]
FYI there is a workaround for this, instead of "dependencies" one can simply make a task executing make with "--cwd" like this:
```

command = "cargo"
args = ["make", "--cwd", "srv1", "start"]
```
, however, I believe that standard approach with "path" should be able to handle this situation as well

**Comment by sagiegurari** [comment]
@strowk cwd and specific env vars will be affected during invocation of parallel.
its actually documented at the end of this section:
https://github.com/sagiegurari/cargo-make#sub-task

> Be aware that parallel invocation of tasks will cause issues if the following feature are used:
> * Setting the task current working directory via cwd attribute will result in all parallel tasks being affected.
> * Avoid using CARGO_MAKE_CURRENT_TASK_ type environment variables as those may hold incorrect values.

there is no isolation as you call it and the cwd is of the current process.
if you do want to run 2 processes in parallel on different cwds, you should use it with the 'fork' attribute (its in same section in the readme as parallel).
this way, changing cwd won't impact both tasks as they are running on different sub processes.

**Comment by sagiegurari** [comment]
@strowk did you try the solution via fork?

**Comment by strowk** [comment]
Aah, got it. Yeah, I did not read docs completely, my bad. Fork works good, big thanks. I think maybe some sort of warning won't hurt, cause without knowing this beforehand, race condition is somewhat hard to pin down.

**Comment by sagiegurari** [comment]
parallel without fork is valid solution for other scenarios. so what/when warning do you recommend?
